### ISSUE TITLE
Do you have an example?

### ISSUE THREAD

**Issue by dvdcastro** [JavascriptMick/angular-reveal-menu#1]
Hello,

I'm trying to use your module. Where do I declare the menu? Do you have a sample presentation?

**Comment by JavascriptMick** [comment]
http://portfolio.michaeldausmann.com/

**Comment by JavascriptMick** [comment]
I have just put a seperate div above the Reveal div in the body of the document...
<div id="menu_container" ng-app="mdportfolio" revealmenu>
